#!/bin/bash
# Restore Script for Bio-medical and signal processing Lab

# Restore Script restores the backup of the data used by the lab.
# Since there is no data being used by Bio-medical and signal processing Lab, 
# the script does nothing. 

# Usage of the script

# To use restore script, run the command
# ./scripts/restore
